plugins: adrv9009_adv: assign correct clojure callback
This seems to be something about which GCC 8 complains about:

```
plugins/adrv9009_adv.c:924:72: error: cast between incompatible function types from 'void (*)(void *)' to 'void (*)(void *, GClosure *)' {aka 'void (*)(void *, struct _GClosure *)'} [-Werror=cast-function-type]
                           G_CALLBACK(signal_handler_cb), data_to_pass, (GClosureNotify)g_free, 0);
```

This wasn't happening before.
It is a good warning, as it can cause stack corruption.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>