plugins/fmcomms1.c: replace abs() with size check
Compiler complains:
```
/Users/travis/build/commodo/iio-oscilloscope/plugins/fmcomms1.c:360:12: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
                        delta = abs(f - data->cal_frequency_MHz);
                                ^
/Users/travis/build/commodo/iio-oscilloscope/plugins/fmcomms1.c:360:12: note: remove the call to 'abs' since unsigned values cannot be negative
                        delta = abs(f - data->cal_frequency_MHz);
                                ^~~
1 error generated.
```

Looking at the code, it is a bit confusing, since one value is `unsigned`,
the other is `unsigned short`. Doing subtraction between them would result
in overflowing to an upper unsigned value.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>