plugins/ad9371*.c: remove unused global var
GCC 8 on OS X complains:
```
/Users/travis/build/commodo/iio-oscilloscope/plugins/ad9371.c:69:21: error: unused variable 'auto_calibrate' [-Werror,-Wunused-variable]
static volatile int auto_calibrate = 0;
```

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>