iio_utils.h: forward declare Gtk structs
Instead of redefining the gtk structs, let's just forward declare.
Otherwise clang was throwing this warning (treated as error):

"error: redefinition of typedef 'GtkToggleToolButton' is a C11 feature
[-Werror,-Wtypedef-redefinition]"

Naturally we could just move to c11, but using the forward declaration
still looks better.

Signed-off-by: Nuno Sa <nuno.sa@analog.com>