osc.c: include `time.h` instead of `sys/time.h`
Error is:
```
/Users/travis/build/commodo/iio-oscilloscope/osc.c:2249:2: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        clock_gettime(CLOCK_MONOTONIC, &ts_current);
```
which is defined in `time.h`.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>